#############################################################################
# Makefile for building: CarHeadUnit
# Generated by qmake (3.1) (Qt 5.15.11)
# Project:  CarHeadUnit.pro
# Template: app
# Command: /usr/bin/qmake -o Makefile CarHeadUnit.pro
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_WEBENGINEWIDGETS_LIB -DQT_PRINTSUPPORT_LIB -DQT_WIDGETS_LIB -DQT_MULTIMEDIA_LIB -DQT_WEBENGINECORE_LIB -DQT_QUICK_LIB -DQT_GUI_LIB -DQT_QMLMODELS_LIB -DQT_WEBCHANNEL_LIB -DQT_QML_LIB -DQT_NETWORK_LIB -DQT_BLUETOOTH_LIB -DQT_DBUS_LIB -DQT_POSITIONING_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -flto -fno-fat-lto-objects -Wall -Wextra -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -O2 -flto -fno-fat-lto-objects -Wall -Wextra -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/qt -I/usr/include/qt/QtWebEngineWidgets -I/usr/include/qt/QtPrintSupport -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtMultimedia -I/usr/include/qt/QtWebEngineCore -I/usr/include/qt/QtQuick -I/usr/include/qt/QtGui -I/usr/include/qt/QtQmlModels -I/usr/include/qt/QtWebChannel -I/usr/include/qt/QtQml -I/usr/include/qt/QtNetwork -I/usr/include/qt/QtBluetooth -I/usr/include/qt/QtDBus -I/usr/include/qt/QtPositioning -I/usr/include/qt/QtCore -Imoc -Iuic -I/usr/lib/qt/mkspecs/linux-g++
QMAKE         = /usr/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/bin/qmake -install qinstall
QINSTALL_PROGRAM = /usr/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = CarHeadUnit1.0.0
DISTDIR = /home/cappe/School/Lab2/CarHeadUnit/obj/CarHeadUnit1.0.0
LINK          = g++
LFLAGS        = -Wl,-O1 -pipe -O2 -flto=8 -fno-fat-lto-objects -fuse-linker-plugin -Wl,-rpath-link,/usr/lib -fPIC
LIBS          = $(SUBLIBS) -ltag -lglib-2.0 /usr/lib/libQt5WebEngineWidgets.so /usr/lib/libQt5PrintSupport.so /usr/lib/libQt5Widgets.so /usr/lib/libQt5Multimedia.so /usr/lib/libQt5WebEngineCore.so /usr/lib/libQt5Quick.so /usr/lib/libQt5Gui.so /usr/lib/libQt5QmlModels.so /usr/lib/libQt5WebChannel.so /usr/lib/libQt5Qml.so /usr/lib/libQt5Network.so /usr/lib/libQt5Bluetooth.so /usr/lib/libQt5DBus.so /usr/lib/libQt5Positioning.so /usr/lib/libQt5Core.so -lGL -lpthread   
AR            = gcc-ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = obj/

####### Files

SOURCES       = APIhandler.cpp \
		appsInterface.cpp \
		audioSystem.cpp \
		buttonHandler.cpp \
		dataStorage.cpp \
		dbusWorker.cpp \
		errorHandling.cpp \
		externalInterfaces.cpp \
		internetConnectivity.cpp \
		main.cpp \
		mainMenu.cpp \
		mainWindow.cpp \
		mediaLibrary.cpp \
		musicInterface.cpp \
		navigationInterface.cpp \
		navigationSystem.cpp \
		radioInterface.cpp \
		settingsManager.cpp \
		statusBar.cpp \
		toolBar.cpp \
		utils.cpp \
		bluetooth/bluetooth.cpp \
		bluetooth/bluetoothInterface.cpp \
		bluetooth/btConnect.cpp \
		bluetooth/btDeviceListener.cpp \
		bluetooth/btDisconnect.cpp \
		bluetooth/btPair.cpp \
		bluetooth/btScan.cpp \
		bluetooth/btUnpair.cpp \
		bluetooth/btDiscoveredDevices.cpp \
		customWidgets/btDevice.cpp \
		customWidgets/customButton.cpp \
		customWidgets/settingsRow.cpp \
		dbus/dbus.cpp moc/moc_btDevice.cpp \
		moc/moc_customButton.cpp \
		moc/moc_settingsRow.cpp \
		moc/moc_APIhandler.cpp \
		moc/moc_bluetooth.cpp \
		moc/moc_bluetoothInterface.cpp \
		moc/moc_buttonHandler.cpp \
		moc/moc_dbusWorker.cpp \
		moc/moc_mainMenu.cpp \
		moc/moc_mainWindow.cpp \
		moc/moc_navigationInterface.cpp \
		moc/moc_radioInterface.cpp \
		moc/moc_statusBar.cpp \
		moc/moc_toolBar.cpp \
		moc/moc_btConnect.cpp \
		moc/moc_btDeviceListener.cpp \
		moc/moc_btDisconnect.cpp \
		moc/moc_btPair.cpp \
		moc/moc_btScan.cpp \
		moc/moc_btUnpair.cpp \
		moc/moc_btDiscoveredDevices.cpp \
		moc/moc_btAbstractClass.cpp \
		moc/moc_dbus.cpp
OBJECTS       = obj/APIhandler.o \
		obj/appsInterface.o \
		obj/audioSystem.o \
		obj/buttonHandler.o \
		obj/dataStorage.o \
		obj/dbusWorker.o \
		obj/errorHandling.o \
		obj/externalInterfaces.o \
		obj/internetConnectivity.o \
		obj/main.o \
		obj/mainMenu.o \
		obj/mainWindow.o \
		obj/mediaLibrary.o \
		obj/musicInterface.o \
		obj/navigationInterface.o \
		obj/navigationSystem.o \
		obj/radioInterface.o \
		obj/settingsManager.o \
		obj/statusBar.o \
		obj/toolBar.o \
		obj/utils.o \
		obj/bluetooth.o \
		obj/bluetoothInterface.o \
		obj/btConnect.o \
		obj/btDeviceListener.o \
		obj/btDisconnect.o \
		obj/btPair.o \
		obj/btScan.o \
		obj/btUnpair.o \
		obj/btDiscoveredDevices.o \
		obj/btDevice.o \
		obj/customButton.o \
		obj/settingsRow.o \
		obj/dbus.o \
		obj/moc_btDevice.o \
		obj/moc_customButton.o \
		obj/moc_settingsRow.o \
		obj/moc_APIhandler.o \
		obj/moc_bluetooth.o \
		obj/moc_bluetoothInterface.o \
		obj/moc_buttonHandler.o \
		obj/moc_dbusWorker.o \
		obj/moc_mainMenu.o \
		obj/moc_mainWindow.o \
		obj/moc_navigationInterface.o \
		obj/moc_radioInterface.o \
		obj/moc_statusBar.o \
		obj/moc_toolBar.o \
		obj/moc_btConnect.o \
		obj/moc_btDeviceListener.o \
		obj/moc_btDisconnect.o \
		obj/moc_btPair.o \
		obj/moc_btScan.o \
		obj/moc_btUnpair.o \
		obj/moc_btDiscoveredDevices.o \
		obj/moc_btAbstractClass.o \
		obj/moc_dbus.o
DIST          = /usr/lib/qt/mkspecs/features/spec_pre.prf \
		/usr/lib/qt/mkspecs/common/unix.conf \
		/usr/lib/qt/mkspecs/common/linux.conf \
		/usr/lib/qt/mkspecs/common/sanitize.conf \
		/usr/lib/qt/mkspecs/common/gcc-base.conf \
		/usr/lib/qt/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/qt/mkspecs/common/g++-base.conf \
		/usr/lib/qt/mkspecs/common/g++-unix.conf \
		/usr/lib/qt/mkspecs/qconfig.pri \
		/usr/lib/qt/mkspecs/modules/qt_Attica.pri \
		/usr/lib/qt/mkspecs/modules/qt_Baloo.pri \
		/usr/lib/qt/mkspecs/modules/qt_BluezQt.pri \
		/usr/lib/qt/mkspecs/modules/qt_KActivities.pri \
		/usr/lib/qt/mkspecs/modules/qt_KActivitiesStats.pri \
		/usr/lib/qt/mkspecs/modules/qt_KArchive.pri \
		/usr/lib/qt/mkspecs/modules/qt_KAuth.pri \
		/usr/lib/qt/mkspecs/modules/qt_KAuthCore.pri \
		/usr/lib/qt/mkspecs/modules/qt_KBookmarks.pri \
		/usr/lib/qt/mkspecs/modules/qt_KCMUtils.pri \
		/usr/lib/qt/mkspecs/modules/qt_KCodecs.pri \
		/usr/lib/qt/mkspecs/modules/qt_KCompletion.pri \
		/usr/lib/qt/mkspecs/modules/qt_KConfigCore.pri \
		/usr/lib/qt/mkspecs/modules/qt_KConfigGui.pri \
		/usr/lib/qt/mkspecs/modules/qt_KConfigWidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_KCoreAddons.pri \
		/usr/lib/qt/mkspecs/modules/qt_KCrash.pri \
		/usr/lib/qt/mkspecs/modules/qt_KDBusAddons.pri \
		/usr/lib/qt/mkspecs/modules/qt_KDeclarative.pri \
		/usr/lib/qt/mkspecs/modules/qt_KDESu.pri \
		/usr/lib/qt/mkspecs/modules/qt_KDNSSD.pri \
		/usr/lib/qt/mkspecs/modules/qt_KDSoapClient.pri \
		/usr/lib/qt/mkspecs/modules/qt_KDSoapServer.pri \
		/usr/lib/qt/mkspecs/modules/qt_KEmoticons.pri \
		/usr/lib/qt/mkspecs/modules/qt_KFileMetaData.pri \
		/usr/lib/qt/mkspecs/modules/qt_KGlobalAccel.pri \
		/usr/lib/qt/mkspecs/modules/qt_KGuiAddons.pri \
		/usr/lib/qt/mkspecs/modules/qt_KHolidays.pri \
		/usr/lib/qt/mkspecs/modules/qt_KI18n.pri \
		/usr/lib/qt/mkspecs/modules/qt_KIconThemes.pri \
		/usr/lib/qt/mkspecs/modules/qt_KIdleTime.pri \
		/usr/lib/qt/mkspecs/modules/qt_KIOCore.pri \
		/usr/lib/qt/mkspecs/modules/qt_KIOFileWidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_KIOGui.pri \
		/usr/lib/qt/mkspecs/modules/qt_KIOWidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_Kirigami2.pri \
		/usr/lib/qt/mkspecs/modules/qt_KItemModels.pri \
		/usr/lib/qt/mkspecs/modules/qt_KItemViews.pri \
		/usr/lib/qt/mkspecs/modules/qt_KJobWidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_KNewStuff.pri \
		/usr/lib/qt/mkspecs/modules/qt_KNewStuffCore.pri \
		/usr/lib/qt/mkspecs/modules/qt_KNotifications.pri \
		/usr/lib/qt/mkspecs/modules/qt_KNotifyConfig.pri \
		/usr/lib/qt/mkspecs/modules/qt_KNTLM.pri \
		/usr/lib/qt/mkspecs/modules/qt_KParts.pri \
		/usr/lib/qt/mkspecs/modules/qt_KPeople.pri \
		/usr/lib/qt/mkspecs/modules/qt_KPeopleWidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_KPty.pri \
		/usr/lib/qt/mkspecs/modules/qt_KRunner.pri \
		/usr/lib/qt/mkspecs/modules/qt_KService.pri \
		/usr/lib/qt/mkspecs/modules/qt_KSyntaxHighlighting.pri \
		/usr/lib/qt/mkspecs/modules/qt_KTextEditor.pri \
		/usr/lib/qt/mkspecs/modules/qt_KTextWidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_KUnitConversion.pri \
		/usr/lib/qt/mkspecs/modules/qt_KUserFeedbackCore.pri \
		/usr/lib/qt/mkspecs/modules/qt_KUserFeedbackWidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_KWallet.pri \
		/usr/lib/qt/mkspecs/modules/qt_KWaylandClient.pri \
		/usr/lib/qt/mkspecs/modules/qt_KWaylandServer.pri \
		/usr/lib/qt/mkspecs/modules/qt_KWidgetsAddons.pri \
		/usr/lib/qt/mkspecs/modules/qt_KWindowSystem.pri \
		/usr/lib/qt/mkspecs/modules/qt_KXmlGui.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_3danimation.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_3danimation_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_3dcore.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_3dcore_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_3dextras.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_3dextras_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_3dinput.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_3dinput_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_3dlogic.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_3dquick.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_3dquick_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_3dquickanimation.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_3dquickextras.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_3dquickinput.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_3dquickrender.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_3drender.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_3drender_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_bluetooth.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_charts.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_charts_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_datavisualization.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_datavisualization_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_designer.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_designer_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_help.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_help_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_location.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_location_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_multimedia_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_multimediagsttools_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_networkauth.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_networkauth_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_nfc.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_nfc_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_pdf.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_pdf_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_pdfwidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_pdfwidgets_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_positioning.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_positioning_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_positioningquick.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_positioningquick_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_purchasing.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_purchasing_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qml_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmlmodels.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmltest_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quick_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickshapes_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quicktemplates2.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_sensors.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_sensors_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_svg.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_svg_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_texttospeech.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_texttospeech_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_uiplugin.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_uitools.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_uitools_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_waylandclient.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_waylandclient_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_waylandcompositor.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_waylandcompositor_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webchannel.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webchannel_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webengine.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webengine_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webenginecore.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webview.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webview_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_x11extras.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_x11extras_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xkbcommon_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_phonon4qt5.pri \
		/usr/lib/qt/mkspecs/modules/qt_Prison.pri \
		/usr/lib/qt/mkspecs/modules/qt_QuickAddons.pri \
		/usr/lib/qt/mkspecs/modules/qt_Solid.pri \
		/usr/lib/qt/mkspecs/modules/qt_SonnetCore.pri \
		/usr/lib/qt/mkspecs/modules/qt_SonnetUi.pri \
		/usr/lib/qt/mkspecs/modules/qt_Syndication.pri \
		/usr/lib/qt/mkspecs/modules/qt_ThreadWeaver.pri \
		/usr/lib/qt/mkspecs/features/qt_functions.prf \
		/usr/lib/qt/mkspecs/features/qt_config.prf \
		/usr/lib/qt/mkspecs/linux-g++/qmake.conf \
		/usr/lib/qt/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/qt/mkspecs/features/exclusive_builds.prf \
		/usr/lib/qt/mkspecs/features/toolchain.prf \
		/usr/lib/qt/mkspecs/features/default_pre.prf \
		/usr/lib/qt/mkspecs/features/resolve_config.prf \
		/usr/lib/qt/mkspecs/features/default_post.prf \
		/usr/lib/qt/mkspecs/features/link_ltcg.prf \
		/usr/lib/qt/mkspecs/features/ltcg.prf \
		/usr/lib/qt/mkspecs/features/warn_on.prf \
		/usr/lib/qt/mkspecs/features/qt.prf \
		/usr/lib/qt/mkspecs/features/resources_functions.prf \
		/usr/lib/qt/mkspecs/features/resources.prf \
		/usr/lib/qt/mkspecs/features/moc.prf \
		/usr/lib/qt/mkspecs/features/dbuscommon.pri \
		/usr/lib/qt/mkspecs/features/dbusinterfaces.prf \
		/usr/lib/qt/mkspecs/features/dbusadaptors.prf \
		/usr/lib/qt/mkspecs/features/unix/opengl.prf \
		/usr/lib/qt/mkspecs/features/uic.prf \
		/usr/lib/qt/mkspecs/features/unix/thread.prf \
		/usr/lib/qt/mkspecs/features/qmake_use.prf \
		/usr/lib/qt/mkspecs/features/file_copies.prf \
		/usr/lib/qt/mkspecs/features/testcase_targets.prf \
		/usr/lib/qt/mkspecs/features/exceptions.prf \
		/usr/lib/qt/mkspecs/features/yacc.prf \
		/usr/lib/qt/mkspecs/features/lex.prf \
		CarHeadUnit.pro customWidgets/btDevice.hpp \
		customWidgets/customButton.hpp \
		customWidgets/settingsRow.hpp \
		headers/APIhandler.hpp \
		headers/appsInterface.hpp \
		headers/audioSystem.hpp \
		headers/bluetooth.hpp \
		headers/bluetoothInterface.hpp \
		headers/buttonHandler.hpp \
		headers/dataStorage.hpp \
		headers/dbusWorker.hpp \
		headers/mainMenu.hpp \
		headers/mainWindow.hpp \
		headers/musicInterface.hpp \
		headers/navigationInterface.hpp \
		headers/navigationSystem.hpp \
		headers/radioInterface.hpp \
		headers/statusBar.hpp \
		headers/toolBar.hpp \
		headers/utils.hpp \
		uic/ui_drawerMenu.h \
		uic/ui_fileBrowser.h \
		uic/ui_musicInterface.h \
		uic/ui_statusBar.h \
		uic/ui_test.h \
		headers/bt/btConnect.hpp \
		headers/bt/btDeviceListener.hpp \
		headers/bt/btDisconnect.hpp \
		headers/bt/btPair.hpp \
		headers/bt/btScan.hpp \
		headers/bt/btUnpair.hpp \
		headers/bt/btDiscoveredDevices.hpp \
		headers/bt/btAbstractClass.hpp \
		headers/dbus/dbus.hpp APIhandler.cpp \
		appsInterface.cpp \
		audioSystem.cpp \
		buttonHandler.cpp \
		dataStorage.cpp \
		dbusWorker.cpp \
		errorHandling.cpp \
		externalInterfaces.cpp \
		internetConnectivity.cpp \
		main.cpp \
		mainMenu.cpp \
		mainWindow.cpp \
		mediaLibrary.cpp \
		musicInterface.cpp \
		navigationInterface.cpp \
		navigationSystem.cpp \
		radioInterface.cpp \
		settingsManager.cpp \
		statusBar.cpp \
		toolBar.cpp \
		utils.cpp \
		bluetooth/bluetooth.cpp \
		bluetooth/bluetoothInterface.cpp \
		bluetooth/btConnect.cpp \
		bluetooth/btDeviceListener.cpp \
		bluetooth/btDisconnect.cpp \
		bluetooth/btPair.cpp \
		bluetooth/btScan.cpp \
		bluetooth/btUnpair.cpp \
		bluetooth/btDiscoveredDevices.cpp \
		customWidgets/btDevice.cpp \
		customWidgets/customButton.cpp \
		customWidgets/settingsRow.cpp \
		dbus/dbus.cpp
QMAKE_TARGET  = CarHeadUnit
DESTDIR       = 
TARGET        = CarHeadUnit


first: all
####### Build rules

CarHeadUnit: uic/ui_test.h uic/ui_drawerMenu.h uic/ui_statusBar.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: CarHeadUnit.pro /usr/lib/qt/mkspecs/linux-g++/qmake.conf /usr/lib/qt/mkspecs/features/spec_pre.prf \
		/usr/lib/qt/mkspecs/common/unix.conf \
		/usr/lib/qt/mkspecs/common/linux.conf \
		/usr/lib/qt/mkspecs/common/sanitize.conf \
		/usr/lib/qt/mkspecs/common/gcc-base.conf \
		/usr/lib/qt/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/qt/mkspecs/common/g++-base.conf \
		/usr/lib/qt/mkspecs/common/g++-unix.conf \
		/usr/lib/qt/mkspecs/qconfig.pri \
		/usr/lib/qt/mkspecs/modules/qt_Attica.pri \
		/usr/lib/qt/mkspecs/modules/qt_Baloo.pri \
		/usr/lib/qt/mkspecs/modules/qt_BluezQt.pri \
		/usr/lib/qt/mkspecs/modules/qt_KActivities.pri \
		/usr/lib/qt/mkspecs/modules/qt_KActivitiesStats.pri \
		/usr/lib/qt/mkspecs/modules/qt_KArchive.pri \
		/usr/lib/qt/mkspecs/modules/qt_KAuth.pri \
		/usr/lib/qt/mkspecs/modules/qt_KAuthCore.pri \
		/usr/lib/qt/mkspecs/modules/qt_KBookmarks.pri \
		/usr/lib/qt/mkspecs/modules/qt_KCMUtils.pri \
		/usr/lib/qt/mkspecs/modules/qt_KCodecs.pri \
		/usr/lib/qt/mkspecs/modules/qt_KCompletion.pri \
		/usr/lib/qt/mkspecs/modules/qt_KConfigCore.pri \
		/usr/lib/qt/mkspecs/modules/qt_KConfigGui.pri \
		/usr/lib/qt/mkspecs/modules/qt_KConfigWidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_KCoreAddons.pri \
		/usr/lib/qt/mkspecs/modules/qt_KCrash.pri \
		/usr/lib/qt/mkspecs/modules/qt_KDBusAddons.pri \
		/usr/lib/qt/mkspecs/modules/qt_KDeclarative.pri \
		/usr/lib/qt/mkspecs/modules/qt_KDESu.pri \
		/usr/lib/qt/mkspecs/modules/qt_KDNSSD.pri \
		/usr/lib/qt/mkspecs/modules/qt_KDSoapClient.pri \
		/usr/lib/qt/mkspecs/modules/qt_KDSoapServer.pri \
		/usr/lib/qt/mkspecs/modules/qt_KEmoticons.pri \
		/usr/lib/qt/mkspecs/modules/qt_KFileMetaData.pri \
		/usr/lib/qt/mkspecs/modules/qt_KGlobalAccel.pri \
		/usr/lib/qt/mkspecs/modules/qt_KGuiAddons.pri \
		/usr/lib/qt/mkspecs/modules/qt_KHolidays.pri \
		/usr/lib/qt/mkspecs/modules/qt_KI18n.pri \
		/usr/lib/qt/mkspecs/modules/qt_KIconThemes.pri \
		/usr/lib/qt/mkspecs/modules/qt_KIdleTime.pri \
		/usr/lib/qt/mkspecs/modules/qt_KIOCore.pri \
		/usr/lib/qt/mkspecs/modules/qt_KIOFileWidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_KIOGui.pri \
		/usr/lib/qt/mkspecs/modules/qt_KIOWidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_Kirigami2.pri \
		/usr/lib/qt/mkspecs/modules/qt_KItemModels.pri \
		/usr/lib/qt/mkspecs/modules/qt_KItemViews.pri \
		/usr/lib/qt/mkspecs/modules/qt_KJobWidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_KNewStuff.pri \
		/usr/lib/qt/mkspecs/modules/qt_KNewStuffCore.pri \
		/usr/lib/qt/mkspecs/modules/qt_KNotifications.pri \
		/usr/lib/qt/mkspecs/modules/qt_KNotifyConfig.pri \
		/usr/lib/qt/mkspecs/modules/qt_KNTLM.pri \
		/usr/lib/qt/mkspecs/modules/qt_KParts.pri \
		/usr/lib/qt/mkspecs/modules/qt_KPeople.pri \
		/usr/lib/qt/mkspecs/modules/qt_KPeopleWidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_KPty.pri \
		/usr/lib/qt/mkspecs/modules/qt_KRunner.pri \
		/usr/lib/qt/mkspecs/modules/qt_KService.pri \
		/usr/lib/qt/mkspecs/modules/qt_KSyntaxHighlighting.pri \
		/usr/lib/qt/mkspecs/modules/qt_KTextEditor.pri \
		/usr/lib/qt/mkspecs/modules/qt_KTextWidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_KUnitConversion.pri \
		/usr/lib/qt/mkspecs/modules/qt_KUserFeedbackCore.pri \
		/usr/lib/qt/mkspecs/modules/qt_KUserFeedbackWidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_KWallet.pri \
		/usr/lib/qt/mkspecs/modules/qt_KWaylandClient.pri \
		/usr/lib/qt/mkspecs/modules/qt_KWaylandServer.pri \
		/usr/lib/qt/mkspecs/modules/qt_KWidgetsAddons.pri \
		/usr/lib/qt/mkspecs/modules/qt_KWindowSystem.pri \
		/usr/lib/qt/mkspecs/modules/qt_KXmlGui.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_3danimation.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_3danimation_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_3dcore.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_3dcore_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_3dextras.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_3dextras_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_3dinput.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_3dinput_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_3dlogic.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_3dquick.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_3dquick_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_3dquickanimation.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_3dquickextras.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_3dquickinput.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_3dquickrender.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_3drender.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_3drender_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_bluetooth.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_charts.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_charts_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_datavisualization.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_datavisualization_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_designer.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_designer_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_help.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_help_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_location.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_location_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_multimedia_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_multimediagsttools_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_networkauth.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_networkauth_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_nfc.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_nfc_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_pdf.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_pdf_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_pdfwidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_pdfwidgets_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_positioning.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_positioning_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_positioningquick.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_positioningquick_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_purchasing.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_purchasing_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qml_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmlmodels.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmltest_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quick_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickshapes_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quicktemplates2.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_sensors.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_sensors_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_svg.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_svg_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_texttospeech.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_texttospeech_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_uiplugin.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_uitools.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_uitools_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_waylandclient.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_waylandclient_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_waylandcompositor.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_waylandcompositor_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webchannel.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webchannel_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webengine.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webengine_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webenginecore.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webview.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webview_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_x11extras.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_x11extras_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xkbcommon_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_phonon4qt5.pri \
		/usr/lib/qt/mkspecs/modules/qt_Prison.pri \
		/usr/lib/qt/mkspecs/modules/qt_QuickAddons.pri \
		/usr/lib/qt/mkspecs/modules/qt_Solid.pri \
		/usr/lib/qt/mkspecs/modules/qt_SonnetCore.pri \
		/usr/lib/qt/mkspecs/modules/qt_SonnetUi.pri \
		/usr/lib/qt/mkspecs/modules/qt_Syndication.pri \
		/usr/lib/qt/mkspecs/modules/qt_ThreadWeaver.pri \
		/usr/lib/qt/mkspecs/features/qt_functions.prf \
		/usr/lib/qt/mkspecs/features/qt_config.prf \
		/usr/lib/qt/mkspecs/linux-g++/qmake.conf \
		/usr/lib/qt/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/qt/mkspecs/features/exclusive_builds.prf \
		/usr/lib/qt/mkspecs/features/toolchain.prf \
		/usr/lib/qt/mkspecs/features/default_pre.prf \
		/usr/lib/qt/mkspecs/features/resolve_config.prf \
		/usr/lib/qt/mkspecs/features/default_post.prf \
		/usr/lib/qt/mkspecs/features/link_ltcg.prf \
		/usr/lib/qt/mkspecs/features/ltcg.prf \
		/usr/lib/qt/mkspecs/features/warn_on.prf \
		/usr/lib/qt/mkspecs/features/qt.prf \
		/usr/lib/qt/mkspecs/features/resources_functions.prf \
		/usr/lib/qt/mkspecs/features/resources.prf \
		/usr/lib/qt/mkspecs/features/moc.prf \
		/usr/lib/qt/mkspecs/features/dbuscommon.pri \
		/usr/lib/qt/mkspecs/features/dbusinterfaces.prf \
		/usr/lib/qt/mkspecs/features/dbusadaptors.prf \
		/usr/lib/qt/mkspecs/features/unix/opengl.prf \
		/usr/lib/qt/mkspecs/features/uic.prf \
		/usr/lib/qt/mkspecs/features/unix/thread.prf \
		/usr/lib/qt/mkspecs/features/qmake_use.prf \
		/usr/lib/qt/mkspecs/features/file_copies.prf \
		/usr/lib/qt/mkspecs/features/testcase_targets.prf \
		/usr/lib/qt/mkspecs/features/exceptions.prf \
		/usr/lib/qt/mkspecs/features/yacc.prf \
		/usr/lib/qt/mkspecs/features/lex.prf \
		CarHeadUnit.pro
	$(QMAKE) -o Makefile CarHeadUnit.pro
/usr/lib/qt/mkspecs/features/spec_pre.prf:
/usr/lib/qt/mkspecs/common/unix.conf:
/usr/lib/qt/mkspecs/common/linux.conf:
/usr/lib/qt/mkspecs/common/sanitize.conf:
/usr/lib/qt/mkspecs/common/gcc-base.conf:
/usr/lib/qt/mkspecs/common/gcc-base-unix.conf:
/usr/lib/qt/mkspecs/common/g++-base.conf:
/usr/lib/qt/mkspecs/common/g++-unix.conf:
/usr/lib/qt/mkspecs/qconfig.pri:
/usr/lib/qt/mkspecs/modules/qt_Attica.pri:
/usr/lib/qt/mkspecs/modules/qt_Baloo.pri:
/usr/lib/qt/mkspecs/modules/qt_BluezQt.pri:
/usr/lib/qt/mkspecs/modules/qt_KActivities.pri:
/usr/lib/qt/mkspecs/modules/qt_KActivitiesStats.pri:
/usr/lib/qt/mkspecs/modules/qt_KArchive.pri:
/usr/lib/qt/mkspecs/modules/qt_KAuth.pri:
/usr/lib/qt/mkspecs/modules/qt_KAuthCore.pri:
/usr/lib/qt/mkspecs/modules/qt_KBookmarks.pri:
/usr/lib/qt/mkspecs/modules/qt_KCMUtils.pri:
/usr/lib/qt/mkspecs/modules/qt_KCodecs.pri:
/usr/lib/qt/mkspecs/modules/qt_KCompletion.pri:
/usr/lib/qt/mkspecs/modules/qt_KConfigCore.pri:
/usr/lib/qt/mkspecs/modules/qt_KConfigGui.pri:
/usr/lib/qt/mkspecs/modules/qt_KConfigWidgets.pri:
/usr/lib/qt/mkspecs/modules/qt_KCoreAddons.pri:
/usr/lib/qt/mkspecs/modules/qt_KCrash.pri:
/usr/lib/qt/mkspecs/modules/qt_KDBusAddons.pri:
/usr/lib/qt/mkspecs/modules/qt_KDeclarative.pri:
/usr/lib/qt/mkspecs/modules/qt_KDESu.pri:
/usr/lib/qt/mkspecs/modules/qt_KDNSSD.pri:
/usr/lib/qt/mkspecs/modules/qt_KDSoapClient.pri:
/usr/lib/qt/mkspecs/modules/qt_KDSoapServer.pri:
/usr/lib/qt/mkspecs/modules/qt_KEmoticons.pri:
/usr/lib/qt/mkspecs/modules/qt_KFileMetaData.pri:
/usr/lib/qt/mkspecs/modules/qt_KGlobalAccel.pri:
/usr/lib/qt/mkspecs/modules/qt_KGuiAddons.pri:
/usr/lib/qt/mkspecs/modules/qt_KHolidays.pri:
/usr/lib/qt/mkspecs/modules/qt_KI18n.pri:
/usr/lib/qt/mkspecs/modules/qt_KIconThemes.pri:
/usr/lib/qt/mkspecs/modules/qt_KIdleTime.pri:
/usr/lib/qt/mkspecs/modules/qt_KIOCore.pri:
/usr/lib/qt/mkspecs/modules/qt_KIOFileWidgets.pri:
/usr/lib/qt/mkspecs/modules/qt_KIOGui.pri:
/usr/lib/qt/mkspecs/modules/qt_KIOWidgets.pri:
/usr/lib/qt/mkspecs/modules/qt_Kirigami2.pri:
/usr/lib/qt/mkspecs/modules/qt_KItemModels.pri:
/usr/lib/qt/mkspecs/modules/qt_KItemViews.pri:
/usr/lib/qt/mkspecs/modules/qt_KJobWidgets.pri:
/usr/lib/qt/mkspecs/modules/qt_KNewStuff.pri:
/usr/lib/qt/mkspecs/modules/qt_KNewStuffCore.pri:
/usr/lib/qt/mkspecs/modules/qt_KNotifications.pri:
/usr/lib/qt/mkspecs/modules/qt_KNotifyConfig.pri:
/usr/lib/qt/mkspecs/modules/qt_KNTLM.pri:
/usr/lib/qt/mkspecs/modules/qt_KParts.pri:
/usr/lib/qt/mkspecs/modules/qt_KPeople.pri:
/usr/lib/qt/mkspecs/modules/qt_KPeopleWidgets.pri:
/usr/lib/qt/mkspecs/modules/qt_KPty.pri:
/usr/lib/qt/mkspecs/modules/qt_KRunner.pri:
/usr/lib/qt/mkspecs/modules/qt_KService.pri:
/usr/lib/qt/mkspecs/modules/qt_KSyntaxHighlighting.pri:
/usr/lib/qt/mkspecs/modules/qt_KTextEditor.pri:
/usr/lib/qt/mkspecs/modules/qt_KTextWidgets.pri:
/usr/lib/qt/mkspecs/modules/qt_KUnitConversion.pri:
/usr/lib/qt/mkspecs/modules/qt_KUserFeedbackCore.pri:
/usr/lib/qt/mkspecs/modules/qt_KUserFeedbackWidgets.pri:
/usr/lib/qt/mkspecs/modules/qt_KWallet.pri:
/usr/lib/qt/mkspecs/modules/qt_KWaylandClient.pri:
/usr/lib/qt/mkspecs/modules/qt_KWaylandServer.pri:
/usr/lib/qt/mkspecs/modules/qt_KWidgetsAddons.pri:
/usr/lib/qt/mkspecs/modules/qt_KWindowSystem.pri:
/usr/lib/qt/mkspecs/modules/qt_KXmlGui.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_3danimation.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_3danimation_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_3dcore.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_3dcore_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_3dextras.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_3dextras_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_3dinput.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_3dinput_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_3dlogic.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_3dlogic_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_3dquick.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_3dquick_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_3dquickanimation.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_3dquickanimation_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_3dquickextras.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_3dquickextras_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_3dquickinput.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_3dquickinput_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_3dquickrender.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_3dquickrender_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_3dquickscene2d.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_3dquickscene2d_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_3drender.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_3drender_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_bluetooth.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_bluetooth_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_charts.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_charts_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_core.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_datavisualization.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_datavisualization_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_designer.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_designer_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_designercomponents_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_edid_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_egl_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_fb_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_glx_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_help.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_help_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_input_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_kms_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_location.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_location_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_multimedia.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_multimedia_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_multimediagsttools_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_multimediawidgets.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_network.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_networkauth.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_networkauth_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_nfc.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_nfc_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_packetprotocol_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_pdf.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_pdf_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_pdfwidgets.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_pdfwidgets_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_positioning.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_positioning_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_positioningquick.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_positioningquick_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_purchasing.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_purchasing_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_qml.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_qml_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_qmldebug_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_qmlmodels.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_qmlmodels_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_qmltest.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_qmltest_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_qmlworkerscript.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_qmlworkerscript_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_quick.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_quick_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_quickcontrols2.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_quickparticles_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_quickshapes_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_quicktemplates2.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_quickwidgets.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_sensors.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_sensors_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_service_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_svg.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_svg_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_texttospeech.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_texttospeech_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_theme_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_uiplugin.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_uitools.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_uitools_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_vulkan_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_waylandclient.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_waylandclient_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_waylandcompositor.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_waylandcompositor_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_webchannel.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_webchannel_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_webengine.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_webengine_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_webenginecore.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_webenginecore_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_webenginewidgets.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_webview.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_webview_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_x11extras.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_x11extras_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_xkbcommon_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_xmlpatterns.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/usr/lib/qt/mkspecs/modules/qt_phonon4qt5.pri:
/usr/lib/qt/mkspecs/modules/qt_Prison.pri:
/usr/lib/qt/mkspecs/modules/qt_QuickAddons.pri:
/usr/lib/qt/mkspecs/modules/qt_Solid.pri:
/usr/lib/qt/mkspecs/modules/qt_SonnetCore.pri:
/usr/lib/qt/mkspecs/modules/qt_SonnetUi.pri:
/usr/lib/qt/mkspecs/modules/qt_Syndication.pri:
/usr/lib/qt/mkspecs/modules/qt_ThreadWeaver.pri:
/usr/lib/qt/mkspecs/features/qt_functions.prf:
/usr/lib/qt/mkspecs/features/qt_config.prf:
/usr/lib/qt/mkspecs/linux-g++/qmake.conf:
/usr/lib/qt/mkspecs/features/spec_post.prf:
.qmake.stash:
/usr/lib/qt/mkspecs/features/exclusive_builds.prf:
/usr/lib/qt/mkspecs/features/toolchain.prf:
/usr/lib/qt/mkspecs/features/default_pre.prf:
/usr/lib/qt/mkspecs/features/resolve_config.prf:
/usr/lib/qt/mkspecs/features/default_post.prf:
/usr/lib/qt/mkspecs/features/link_ltcg.prf:
/usr/lib/qt/mkspecs/features/ltcg.prf:
/usr/lib/qt/mkspecs/features/warn_on.prf:
/usr/lib/qt/mkspecs/features/qt.prf:
/usr/lib/qt/mkspecs/features/resources_functions.prf:
/usr/lib/qt/mkspecs/features/resources.prf:
/usr/lib/qt/mkspecs/features/moc.prf:
/usr/lib/qt/mkspecs/features/dbuscommon.pri:
/usr/lib/qt/mkspecs/features/dbusinterfaces.prf:
/usr/lib/qt/mkspecs/features/dbusadaptors.prf:
/usr/lib/qt/mkspecs/features/unix/opengl.prf:
/usr/lib/qt/mkspecs/features/uic.prf:
/usr/lib/qt/mkspecs/features/unix/thread.prf:
/usr/lib/qt/mkspecs/features/qmake_use.prf:
/usr/lib/qt/mkspecs/features/file_copies.prf:
/usr/lib/qt/mkspecs/features/testcase_targets.prf:
/usr/lib/qt/mkspecs/features/exceptions.prf:
/usr/lib/qt/mkspecs/features/yacc.prf:
/usr/lib/qt/mkspecs/features/lex.prf:
CarHeadUnit.pro:
qmake: FORCE
	@$(QMAKE) -o Makefile CarHeadUnit.pro

qmake_all: FORCE


all: Makefile CarHeadUnit

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents /usr/lib/qt/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents customWidgets/btDevice.hpp customWidgets/customButton.hpp customWidgets/settingsRow.hpp headers/APIhandler.hpp headers/appsInterface.hpp headers/audioSystem.hpp headers/bluetooth.hpp headers/bluetoothInterface.hpp headers/buttonHandler.hpp headers/dataStorage.hpp headers/dbusWorker.hpp headers/mainMenu.hpp headers/mainWindow.hpp headers/musicInterface.hpp headers/navigationInterface.hpp headers/navigationSystem.hpp headers/radioInterface.hpp headers/statusBar.hpp headers/toolBar.hpp headers/utils.hpp uic/ui_drawerMenu.h uic/ui_fileBrowser.h uic/ui_musicInterface.h uic/ui_statusBar.h uic/ui_test.h headers/bt/btConnect.hpp headers/bt/btDeviceListener.hpp headers/bt/btDisconnect.hpp headers/bt/btPair.hpp headers/bt/btScan.hpp headers/bt/btUnpair.hpp headers/bt/btDiscoveredDevices.hpp headers/bt/btAbstractClass.hpp headers/dbus/dbus.hpp $(DISTDIR)/
	$(COPY_FILE) --parents APIhandler.cpp appsInterface.cpp audioSystem.cpp buttonHandler.cpp dataStorage.cpp dbusWorker.cpp errorHandling.cpp externalInterfaces.cpp internetConnectivity.cpp main.cpp mainMenu.cpp mainWindow.cpp mediaLibrary.cpp musicInterface.cpp navigationInterface.cpp navigationSystem.cpp radioInterface.cpp settingsManager.cpp statusBar.cpp toolBar.cpp utils.cpp bluetooth/bluetooth.cpp bluetooth/bluetoothInterface.cpp bluetooth/btConnect.cpp bluetooth/btDeviceListener.cpp bluetooth/btDisconnect.cpp bluetooth/btPair.cpp bluetooth/btScan.cpp bluetooth/btUnpair.cpp bluetooth/btDiscoveredDevices.cpp customWidgets/btDevice.cpp customWidgets/customButton.cpp customWidgets/settingsRow.cpp dbus/dbus.cpp $(DISTDIR)/
	$(COPY_FILE) --parents test.ui ui/drawerMenu.ui ui/statusBar.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_predefs_make_all: moc/moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc/moc_predefs.h
moc/moc_predefs.h: /usr/lib/qt/mkspecs/features/data/dummy.cpp
	g++ -pipe -O2 -flto -fno-fat-lto-objects -Wall -Wextra -dM -E -o moc/moc_predefs.h /usr/lib/qt/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc/moc_btDevice.cpp moc/moc_customButton.cpp moc/moc_settingsRow.cpp moc/moc_APIhandler.cpp moc/moc_bluetooth.cpp moc/moc_bluetoothInterface.cpp moc/moc_buttonHandler.cpp moc/moc_dbusWorker.cpp moc/moc_mainMenu.cpp moc/moc_mainWindow.cpp moc/moc_navigationInterface.cpp moc/moc_radioInterface.cpp moc/moc_statusBar.cpp moc/moc_toolBar.cpp moc/moc_btConnect.cpp moc/moc_btDeviceListener.cpp moc/moc_btDisconnect.cpp moc/moc_btPair.cpp moc/moc_btScan.cpp moc/moc_btUnpair.cpp moc/moc_btDiscoveredDevices.cpp moc/moc_btAbstractClass.cpp moc/moc_dbus.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc/moc_btDevice.cpp moc/moc_customButton.cpp moc/moc_settingsRow.cpp moc/moc_APIhandler.cpp moc/moc_bluetooth.cpp moc/moc_bluetoothInterface.cpp moc/moc_buttonHandler.cpp moc/moc_dbusWorker.cpp moc/moc_mainMenu.cpp moc/moc_mainWindow.cpp moc/moc_navigationInterface.cpp moc/moc_radioInterface.cpp moc/moc_statusBar.cpp moc/moc_toolBar.cpp moc/moc_btConnect.cpp moc/moc_btDeviceListener.cpp moc/moc_btDisconnect.cpp moc/moc_btPair.cpp moc/moc_btScan.cpp moc/moc_btUnpair.cpp moc/moc_btDiscoveredDevices.cpp moc/moc_btAbstractClass.cpp moc/moc_dbus.cpp
moc/moc_btDevice.cpp: customWidgets/btDevice.hpp \
		headers/bt/btDeviceListener.hpp \
		moc/moc_predefs.h \
		/usr/bin/moc
	/usr/bin/moc $(DEFINES) --include /home/cappe/School/Lab2/CarHeadUnit/moc/moc_predefs.h -I/usr/lib/qt/mkspecs/linux-g++ -I/home/cappe/School/Lab2/CarHeadUnit -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/qt -I/usr/include/qt/QtWebEngineWidgets -I/usr/include/qt/QtPrintSupport -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtMultimedia -I/usr/include/qt/QtWebEngineCore -I/usr/include/qt/QtQuick -I/usr/include/qt/QtGui -I/usr/include/qt/QtQmlModels -I/usr/include/qt/QtWebChannel -I/usr/include/qt/QtQml -I/usr/include/qt/QtNetwork -I/usr/include/qt/QtBluetooth -I/usr/include/qt/QtDBus -I/usr/include/qt/QtPositioning -I/usr/include/qt/QtCore -I/usr/include/c++/13.2.1 -I/usr/include/c++/13.2.1/x86_64-pc-linux-gnu -I/usr/include/c++/13.2.1/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/13.2.1/include -I/usr/local/include -I/usr/lib/gcc/x86_64-pc-linux-gnu/13.2.1/include-fixed -I/usr/include customWidgets/btDevice.hpp -o moc/moc_btDevice.cpp

moc/moc_customButton.cpp: customWidgets/customButton.hpp \
		moc/moc_predefs.h \
		/usr/bin/moc
	/usr/bin/moc $(DEFINES) --include /home/cappe/School/Lab2/CarHeadUnit/moc/moc_predefs.h -I/usr/lib/qt/mkspecs/linux-g++ -I/home/cappe/School/Lab2/CarHeadUnit -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/qt -I/usr/include/qt/QtWebEngineWidgets -I/usr/include/qt/QtPrintSupport -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtMultimedia -I/usr/include/qt/QtWebEngineCore -I/usr/include/qt/QtQuick -I/usr/include/qt/QtGui -I/usr/include/qt/QtQmlModels -I/usr/include/qt/QtWebChannel -I/usr/include/qt/QtQml -I/usr/include/qt/QtNetwork -I/usr/include/qt/QtBluetooth -I/usr/include/qt/QtDBus -I/usr/include/qt/QtPositioning -I/usr/include/qt/QtCore -I/usr/include/c++/13.2.1 -I/usr/include/c++/13.2.1/x86_64-pc-linux-gnu -I/usr/include/c++/13.2.1/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/13.2.1/include -I/usr/local/include -I/usr/lib/gcc/x86_64-pc-linux-gnu/13.2.1/include-fixed -I/usr/include customWidgets/customButton.hpp -o moc/moc_customButton.cpp

moc/moc_settingsRow.cpp: customWidgets/settingsRow.hpp \
		moc/moc_predefs.h \
		/usr/bin/moc
	/usr/bin/moc $(DEFINES) --include /home/cappe/School/Lab2/CarHeadUnit/moc/moc_predefs.h -I/usr/lib/qt/mkspecs/linux-g++ -I/home/cappe/School/Lab2/CarHeadUnit -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/qt -I/usr/include/qt/QtWebEngineWidgets -I/usr/include/qt/QtPrintSupport -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtMultimedia -I/usr/include/qt/QtWebEngineCore -I/usr/include/qt/QtQuick -I/usr/include/qt/QtGui -I/usr/include/qt/QtQmlModels -I/usr/include/qt/QtWebChannel -I/usr/include/qt/QtQml -I/usr/include/qt/QtNetwork -I/usr/include/qt/QtBluetooth -I/usr/include/qt/QtDBus -I/usr/include/qt/QtPositioning -I/usr/include/qt/QtCore -I/usr/include/c++/13.2.1 -I/usr/include/c++/13.2.1/x86_64-pc-linux-gnu -I/usr/include/c++/13.2.1/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/13.2.1/include -I/usr/local/include -I/usr/lib/gcc/x86_64-pc-linux-gnu/13.2.1/include-fixed -I/usr/include customWidgets/settingsRow.hpp -o moc/moc_settingsRow.cpp

moc/moc_APIhandler.cpp: headers/APIhandler.hpp \
		moc/moc_predefs.h \
		/usr/bin/moc
	/usr/bin/moc $(DEFINES) --include /home/cappe/School/Lab2/CarHeadUnit/moc/moc_predefs.h -I/usr/lib/qt/mkspecs/linux-g++ -I/home/cappe/School/Lab2/CarHeadUnit -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/qt -I/usr/include/qt/QtWebEngineWidgets -I/usr/include/qt/QtPrintSupport -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtMultimedia -I/usr/include/qt/QtWebEngineCore -I/usr/include/qt/QtQuick -I/usr/include/qt/QtGui -I/usr/include/qt/QtQmlModels -I/usr/include/qt/QtWebChannel -I/usr/include/qt/QtQml -I/usr/include/qt/QtNetwork -I/usr/include/qt/QtBluetooth -I/usr/include/qt/QtDBus -I/usr/include/qt/QtPositioning -I/usr/include/qt/QtCore -I/usr/include/c++/13.2.1 -I/usr/include/c++/13.2.1/x86_64-pc-linux-gnu -I/usr/include/c++/13.2.1/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/13.2.1/include -I/usr/local/include -I/usr/lib/gcc/x86_64-pc-linux-gnu/13.2.1/include-fixed -I/usr/include headers/APIhandler.hpp -o moc/moc_APIhandler.cpp

moc/moc_bluetooth.cpp: headers/bluetooth.hpp \
		moc/moc_predefs.h \
		/usr/bin/moc
	/usr/bin/moc $(DEFINES) --include /home/cappe/School/Lab2/CarHeadUnit/moc/moc_predefs.h -I/usr/lib/qt/mkspecs/linux-g++ -I/home/cappe/School/Lab2/CarHeadUnit -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/qt -I/usr/include/qt/QtWebEngineWidgets -I/usr/include/qt/QtPrintSupport -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtMultimedia -I/usr/include/qt/QtWebEngineCore -I/usr/include/qt/QtQuick -I/usr/include/qt/QtGui -I/usr/include/qt/QtQmlModels -I/usr/include/qt/QtWebChannel -I/usr/include/qt/QtQml -I/usr/include/qt/QtNetwork -I/usr/include/qt/QtBluetooth -I/usr/include/qt/QtDBus -I/usr/include/qt/QtPositioning -I/usr/include/qt/QtCore -I/usr/include/c++/13.2.1 -I/usr/include/c++/13.2.1/x86_64-pc-linux-gnu -I/usr/include/c++/13.2.1/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/13.2.1/include -I/usr/local/include -I/usr/lib/gcc/x86_64-pc-linux-gnu/13.2.1/include-fixed -I/usr/include headers/bluetooth.hpp -o moc/moc_bluetooth.cpp

moc/moc_bluetoothInterface.cpp: headers/bluetoothInterface.hpp \
		customWidgets/settingsRow.hpp \
		customWidgets/btDevice.hpp \
		headers/bt/btDeviceListener.hpp \
		headers/dbus/dbus.hpp \
		headers/bt/btDiscoveredDevices.hpp \
		headers/bt/btDisconnect.hpp \
		headers/bt/btConnect.hpp \
		headers/bt/btAbstractClass.hpp \
		headers/bt/btUnpair.hpp \
		headers/bt/btScan.hpp \
		headers/bt/btPair.hpp \
		headers/bluetooth.hpp \
		moc/moc_predefs.h \
		/usr/bin/moc
	/usr/bin/moc $(DEFINES) --include /home/cappe/School/Lab2/CarHeadUnit/moc/moc_predefs.h -I/usr/lib/qt/mkspecs/linux-g++ -I/home/cappe/School/Lab2/CarHeadUnit -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/qt -I/usr/include/qt/QtWebEngineWidgets -I/usr/include/qt/QtPrintSupport -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtMultimedia -I/usr/include/qt/QtWebEngineCore -I/usr/include/qt/QtQuick -I/usr/include/qt/QtGui -I/usr/include/qt/QtQmlModels -I/usr/include/qt/QtWebChannel -I/usr/include/qt/QtQml -I/usr/include/qt/QtNetwork -I/usr/include/qt/QtBluetooth -I/usr/include/qt/QtDBus -I/usr/include/qt/QtPositioning -I/usr/include/qt/QtCore -I/usr/include/c++/13.2.1 -I/usr/include/c++/13.2.1/x86_64-pc-linux-gnu -I/usr/include/c++/13.2.1/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/13.2.1/include -I/usr/local/include -I/usr/lib/gcc/x86_64-pc-linux-gnu/13.2.1/include-fixed -I/usr/include headers/bluetoothInterface.hpp -o moc/moc_bluetoothInterface.cpp

moc/moc_buttonHandler.cpp: headers/buttonHandler.hpp \
		moc/moc_predefs.h \
		/usr/bin/moc
	/usr/bin/moc $(DEFINES) --include /home/cappe/School/Lab2/CarHeadUnit/moc/moc_predefs.h -I/usr/lib/qt/mkspecs/linux-g++ -I/home/cappe/School/Lab2/CarHeadUnit -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/qt -I/usr/include/qt/QtWebEngineWidgets -I/usr/include/qt/QtPrintSupport -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtMultimedia -I/usr/include/qt/QtWebEngineCore -I/usr/include/qt/QtQuick -I/usr/include/qt/QtGui -I/usr/include/qt/QtQmlModels -I/usr/include/qt/QtWebChannel -I/usr/include/qt/QtQml -I/usr/include/qt/QtNetwork -I/usr/include/qt/QtBluetooth -I/usr/include/qt/QtDBus -I/usr/include/qt/QtPositioning -I/usr/include/qt/QtCore -I/usr/include/c++/13.2.1 -I/usr/include/c++/13.2.1/x86_64-pc-linux-gnu -I/usr/include/c++/13.2.1/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/13.2.1/include -I/usr/local/include -I/usr/lib/gcc/x86_64-pc-linux-gnu/13.2.1/include-fixed -I/usr/include headers/buttonHandler.hpp -o moc/moc_buttonHandler.cpp

moc/moc_dbusWorker.cpp: headers/dbusWorker.hpp \
		headers/bluetooth.hpp \
		moc/moc_predefs.h \
		/usr/bin/moc
	/usr/bin/moc $(DEFINES) --include /home/cappe/School/Lab2/CarHeadUnit/moc/moc_predefs.h -I/usr/lib/qt/mkspecs/linux-g++ -I/home/cappe/School/Lab2/CarHeadUnit -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/qt -I/usr/include/qt/QtWebEngineWidgets -I/usr/include/qt/QtPrintSupport -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtMultimedia -I/usr/include/qt/QtWebEngineCore -I/usr/include/qt/QtQuick -I/usr/include/qt/QtGui -I/usr/include/qt/QtQmlModels -I/usr/include/qt/QtWebChannel -I/usr/include/qt/QtQml -I/usr/include/qt/QtNetwork -I/usr/include/qt/QtBluetooth -I/usr/include/qt/QtDBus -I/usr/include/qt/QtPositioning -I/usr/include/qt/QtCore -I/usr/include/c++/13.2.1 -I/usr/include/c++/13.2.1/x86_64-pc-linux-gnu -I/usr/include/c++/13.2.1/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/13.2.1/include -I/usr/local/include -I/usr/lib/gcc/x86_64-pc-linux-gnu/13.2.1/include-fixed -I/usr/include headers/dbusWorker.hpp -o moc/moc_dbusWorker.cpp

moc/moc_mainMenu.cpp: headers/mainMenu.hpp \
		uic/ui_test.h \
		customWidgets/customButton.hpp \
		moc/moc_predefs.h \
		/usr/bin/moc
	/usr/bin/moc $(DEFINES) --include /home/cappe/School/Lab2/CarHeadUnit/moc/moc_predefs.h -I/usr/lib/qt/mkspecs/linux-g++ -I/home/cappe/School/Lab2/CarHeadUnit -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/qt -I/usr/include/qt/QtWebEngineWidgets -I/usr/include/qt/QtPrintSupport -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtMultimedia -I/usr/include/qt/QtWebEngineCore -I/usr/include/qt/QtQuick -I/usr/include/qt/QtGui -I/usr/include/qt/QtQmlModels -I/usr/include/qt/QtWebChannel -I/usr/include/qt/QtQml -I/usr/include/qt/QtNetwork -I/usr/include/qt/QtBluetooth -I/usr/include/qt/QtDBus -I/usr/include/qt/QtPositioning -I/usr/include/qt/QtCore -I/usr/include/c++/13.2.1 -I/usr/include/c++/13.2.1/x86_64-pc-linux-gnu -I/usr/include/c++/13.2.1/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/13.2.1/include -I/usr/local/include -I/usr/lib/gcc/x86_64-pc-linux-gnu/13.2.1/include-fixed -I/usr/include headers/mainMenu.hpp -o moc/moc_mainMenu.cpp

moc/moc_mainWindow.cpp: headers/mainWindow.hpp \
		headers/bt/btDeviceListener.hpp \
		moc/moc_predefs.h \
		/usr/bin/moc
	/usr/bin/moc $(DEFINES) --include /home/cappe/School/Lab2/CarHeadUnit/moc/moc_predefs.h -I/usr/lib/qt/mkspecs/linux-g++ -I/home/cappe/School/Lab2/CarHeadUnit -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/qt -I/usr/include/qt/QtWebEngineWidgets -I/usr/include/qt/QtPrintSupport -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtMultimedia -I/usr/include/qt/QtWebEngineCore -I/usr/include/qt/QtQuick -I/usr/include/qt/QtGui -I/usr/include/qt/QtQmlModels -I/usr/include/qt/QtWebChannel -I/usr/include/qt/QtQml -I/usr/include/qt/QtNetwork -I/usr/include/qt/QtBluetooth -I/usr/include/qt/QtDBus -I/usr/include/qt/QtPositioning -I/usr/include/qt/QtCore -I/usr/include/c++/13.2.1 -I/usr/include/c++/13.2.1/x86_64-pc-linux-gnu -I/usr/include/c++/13.2.1/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/13.2.1/include -I/usr/local/include -I/usr/lib/gcc/x86_64-pc-linux-gnu/13.2.1/include-fixed -I/usr/include headers/mainWindow.hpp -o moc/moc_mainWindow.cpp

moc/moc_navigationInterface.cpp: headers/navigationInterface.hpp \
		headers/navigationSystem.hpp \
		moc/moc_predefs.h \
		/usr/bin/moc
	/usr/bin/moc $(DEFINES) --include /home/cappe/School/Lab2/CarHeadUnit/moc/moc_predefs.h -I/usr/lib/qt/mkspecs/linux-g++ -I/home/cappe/School/Lab2/CarHeadUnit -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/qt -I/usr/include/qt/QtWebEngineWidgets -I/usr/include/qt/QtPrintSupport -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtMultimedia -I/usr/include/qt/QtWebEngineCore -I/usr/include/qt/QtQuick -I/usr/include/qt/QtGui -I/usr/include/qt/QtQmlModels -I/usr/include/qt/QtWebChannel -I/usr/include/qt/QtQml -I/usr/include/qt/QtNetwork -I/usr/include/qt/QtBluetooth -I/usr/include/qt/QtDBus -I/usr/include/qt/QtPositioning -I/usr/include/qt/QtCore -I/usr/include/c++/13.2.1 -I/usr/include/c++/13.2.1/x86_64-pc-linux-gnu -I/usr/include/c++/13.2.1/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/13.2.1/include -I/usr/local/include -I/usr/lib/gcc/x86_64-pc-linux-gnu/13.2.1/include-fixed -I/usr/include headers/navigationInterface.hpp -o moc/moc_navigationInterface.cpp

moc/moc_radioInterface.cpp: headers/radioInterface.hpp \
		customWidgets/customButton.hpp \
		headers/dataStorage.hpp \
		headers/APIhandler.hpp \
		moc/moc_predefs.h \
		/usr/bin/moc
	/usr/bin/moc $(DEFINES) --include /home/cappe/School/Lab2/CarHeadUnit/moc/moc_predefs.h -I/usr/lib/qt/mkspecs/linux-g++ -I/home/cappe/School/Lab2/CarHeadUnit -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/qt -I/usr/include/qt/QtWebEngineWidgets -I/usr/include/qt/QtPrintSupport -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtMultimedia -I/usr/include/qt/QtWebEngineCore -I/usr/include/qt/QtQuick -I/usr/include/qt/QtGui -I/usr/include/qt/QtQmlModels -I/usr/include/qt/QtWebChannel -I/usr/include/qt/QtQml -I/usr/include/qt/QtNetwork -I/usr/include/qt/QtBluetooth -I/usr/include/qt/QtDBus -I/usr/include/qt/QtPositioning -I/usr/include/qt/QtCore -I/usr/include/c++/13.2.1 -I/usr/include/c++/13.2.1/x86_64-pc-linux-gnu -I/usr/include/c++/13.2.1/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/13.2.1/include -I/usr/local/include -I/usr/lib/gcc/x86_64-pc-linux-gnu/13.2.1/include-fixed -I/usr/include headers/radioInterface.hpp -o moc/moc_radioInterface.cpp

moc/moc_statusBar.cpp: headers/statusBar.hpp \
		uic/ui_statusBar.h \
		moc/moc_predefs.h \
		/usr/bin/moc
	/usr/bin/moc $(DEFINES) --include /home/cappe/School/Lab2/CarHeadUnit/moc/moc_predefs.h -I/usr/lib/qt/mkspecs/linux-g++ -I/home/cappe/School/Lab2/CarHeadUnit -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/qt -I/usr/include/qt/QtWebEngineWidgets -I/usr/include/qt/QtPrintSupport -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtMultimedia -I/usr/include/qt/QtWebEngineCore -I/usr/include/qt/QtQuick -I/usr/include/qt/QtGui -I/usr/include/qt/QtQmlModels -I/usr/include/qt/QtWebChannel -I/usr/include/qt/QtQml -I/usr/include/qt/QtNetwork -I/usr/include/qt/QtBluetooth -I/usr/include/qt/QtDBus -I/usr/include/qt/QtPositioning -I/usr/include/qt/QtCore -I/usr/include/c++/13.2.1 -I/usr/include/c++/13.2.1/x86_64-pc-linux-gnu -I/usr/include/c++/13.2.1/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/13.2.1/include -I/usr/local/include -I/usr/lib/gcc/x86_64-pc-linux-gnu/13.2.1/include-fixed -I/usr/include headers/statusBar.hpp -o moc/moc_statusBar.cpp

moc/moc_toolBar.cpp: headers/toolBar.hpp \
		uic/ui_drawerMenu.h \
		moc/moc_predefs.h \
		/usr/bin/moc
	/usr/bin/moc $(DEFINES) --include /home/cappe/School/Lab2/CarHeadUnit/moc/moc_predefs.h -I/usr/lib/qt/mkspecs/linux-g++ -I/home/cappe/School/Lab2/CarHeadUnit -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/qt -I/usr/include/qt/QtWebEngineWidgets -I/usr/include/qt/QtPrintSupport -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtMultimedia -I/usr/include/qt/QtWebEngineCore -I/usr/include/qt/QtQuick -I/usr/include/qt/QtGui -I/usr/include/qt/QtQmlModels -I/usr/include/qt/QtWebChannel -I/usr/include/qt/QtQml -I/usr/include/qt/QtNetwork -I/usr/include/qt/QtBluetooth -I/usr/include/qt/QtDBus -I/usr/include/qt/QtPositioning -I/usr/include/qt/QtCore -I/usr/include/c++/13.2.1 -I/usr/include/c++/13.2.1/x86_64-pc-linux-gnu -I/usr/include/c++/13.2.1/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/13.2.1/include -I/usr/local/include -I/usr/lib/gcc/x86_64-pc-linux-gnu/13.2.1/include-fixed -I/usr/include headers/toolBar.hpp -o moc/moc_toolBar.cpp

moc/moc_btConnect.cpp: headers/bt/btConnect.hpp \
		headers/dbus/dbus.hpp \
		headers/bt/btAbstractClass.hpp \
		moc/moc_predefs.h \
		/usr/bin/moc
	/usr/bin/moc $(DEFINES) --include /home/cappe/School/Lab2/CarHeadUnit/moc/moc_predefs.h -I/usr/lib/qt/mkspecs/linux-g++ -I/home/cappe/School/Lab2/CarHeadUnit -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/qt -I/usr/include/qt/QtWebEngineWidgets -I/usr/include/qt/QtPrintSupport -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtMultimedia -I/usr/include/qt/QtWebEngineCore -I/usr/include/qt/QtQuick -I/usr/include/qt/QtGui -I/usr/include/qt/QtQmlModels -I/usr/include/qt/QtWebChannel -I/usr/include/qt/QtQml -I/usr/include/qt/QtNetwork -I/usr/include/qt/QtBluetooth -I/usr/include/qt/QtDBus -I/usr/include/qt/QtPositioning -I/usr/include/qt/QtCore -I/usr/include/c++/13.2.1 -I/usr/include/c++/13.2.1/x86_64-pc-linux-gnu -I/usr/include/c++/13.2.1/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/13.2.1/include -I/usr/local/include -I/usr/lib/gcc/x86_64-pc-linux-gnu/13.2.1/include-fixed -I/usr/include headers/bt/btConnect.hpp -o moc/moc_btConnect.cpp

moc/moc_btDeviceListener.cpp: headers/bt/btDeviceListener.hpp \
		moc/moc_predefs.h \
		/usr/bin/moc
	/usr/bin/moc $(DEFINES) --include /home/cappe/School/Lab2/CarHeadUnit/moc/moc_predefs.h -I/usr/lib/qt/mkspecs/linux-g++ -I/home/cappe/School/Lab2/CarHeadUnit -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/qt -I/usr/include/qt/QtWebEngineWidgets -I/usr/include/qt/QtPrintSupport -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtMultimedia -I/usr/include/qt/QtWebEngineCore -I/usr/include/qt/QtQuick -I/usr/include/qt/QtGui -I/usr/include/qt/QtQmlModels -I/usr/include/qt/QtWebChannel -I/usr/include/qt/QtQml -I/usr/include/qt/QtNetwork -I/usr/include/qt/QtBluetooth -I/usr/include/qt/QtDBus -I/usr/include/qt/QtPositioning -I/usr/include/qt/QtCore -I/usr/include/c++/13.2.1 -I/usr/include/c++/13.2.1/x86_64-pc-linux-gnu -I/usr/include/c++/13.2.1/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/13.2.1/include -I/usr/local/include -I/usr/lib/gcc/x86_64-pc-linux-gnu/13.2.1/include-fixed -I/usr/include headers/bt/btDeviceListener.hpp -o moc/moc_btDeviceListener.cpp

moc/moc_btDisconnect.cpp: headers/bt/btDisconnect.hpp \
		headers/dbus/dbus.hpp \
		moc/moc_predefs.h \
		/usr/bin/moc
	/usr/bin/moc $(DEFINES) --include /home/cappe/School/Lab2/CarHeadUnit/moc/moc_predefs.h -I/usr/lib/qt/mkspecs/linux-g++ -I/home/cappe/School/Lab2/CarHeadUnit -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/qt -I/usr/include/qt/QtWebEngineWidgets -I/usr/include/qt/QtPrintSupport -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtMultimedia -I/usr/include/qt/QtWebEngineCore -I/usr/include/qt/QtQuick -I/usr/include/qt/QtGui -I/usr/include/qt/QtQmlModels -I/usr/include/qt/QtWebChannel -I/usr/include/qt/QtQml -I/usr/include/qt/QtNetwork -I/usr/include/qt/QtBluetooth -I/usr/include/qt/QtDBus -I/usr/include/qt/QtPositioning -I/usr/include/qt/QtCore -I/usr/include/c++/13.2.1 -I/usr/include/c++/13.2.1/x86_64-pc-linux-gnu -I/usr/include/c++/13.2.1/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/13.2.1/include -I/usr/local/include -I/usr/lib/gcc/x86_64-pc-linux-gnu/13.2.1/include-fixed -I/usr/include headers/bt/btDisconnect.hpp -o moc/moc_btDisconnect.cpp

moc/moc_btPair.cpp: headers/bt/btPair.hpp \
		headers/dbus/dbus.hpp \
		moc/moc_predefs.h \
		/usr/bin/moc
	/usr/bin/moc $(DEFINES) --include /home/cappe/School/Lab2/CarHeadUnit/moc/moc_predefs.h -I/usr/lib/qt/mkspecs/linux-g++ -I/home/cappe/School/Lab2/CarHeadUnit -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/qt -I/usr/include/qt/QtWebEngineWidgets -I/usr/include/qt/QtPrintSupport -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtMultimedia -I/usr/include/qt/QtWebEngineCore -I/usr/include/qt/QtQuick -I/usr/include/qt/QtGui -I/usr/include/qt/QtQmlModels -I/usr/include/qt/QtWebChannel -I/usr/include/qt/QtQml -I/usr/include/qt/QtNetwork -I/usr/include/qt/QtBluetooth -I/usr/include/qt/QtDBus -I/usr/include/qt/QtPositioning -I/usr/include/qt/QtCore -I/usr/include/c++/13.2.1 -I/usr/include/c++/13.2.1/x86_64-pc-linux-gnu -I/usr/include/c++/13.2.1/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/13.2.1/include -I/usr/local/include -I/usr/lib/gcc/x86_64-pc-linux-gnu/13.2.1/include-fixed -I/usr/include headers/bt/btPair.hpp -o moc/moc_btPair.cpp

moc/moc_btScan.cpp: headers/bt/btScan.hpp \
		headers/dbus/dbus.hpp \
		moc/moc_predefs.h \
		/usr/bin/moc
	/usr/bin/moc $(DEFINES) --include /home/cappe/School/Lab2/CarHeadUnit/moc/moc_predefs.h -I/usr/lib/qt/mkspecs/linux-g++ -I/home/cappe/School/Lab2/CarHeadUnit -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/qt -I/usr/include/qt/QtWebEngineWidgets -I/usr/include/qt/QtPrintSupport -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtMultimedia -I/usr/include/qt/QtWebEngineCore -I/usr/include/qt/QtQuick -I/usr/include/qt/QtGui -I/usr/include/qt/QtQmlModels -I/usr/include/qt/QtWebChannel -I/usr/include/qt/QtQml -I/usr/include/qt/QtNetwork -I/usr/include/qt/QtBluetooth -I/usr/include/qt/QtDBus -I/usr/include/qt/QtPositioning -I/usr/include/qt/QtCore -I/usr/include/c++/13.2.1 -I/usr/include/c++/13.2.1/x86_64-pc-linux-gnu -I/usr/include/c++/13.2.1/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/13.2.1/include -I/usr/local/include -I/usr/lib/gcc/x86_64-pc-linux-gnu/13.2.1/include-fixed -I/usr/include headers/bt/btScan.hpp -o moc/moc_btScan.cpp

moc/moc_btUnpair.cpp: headers/bt/btUnpair.hpp \
		headers/dbus/dbus.hpp \
		moc/moc_predefs.h \
		/usr/bin/moc
	/usr/bin/moc $(DEFINES) --include /home/cappe/School/Lab2/CarHeadUnit/moc/moc_predefs.h -I/usr/lib/qt/mkspecs/linux-g++ -I/home/cappe/School/Lab2/CarHeadUnit -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/qt -I/usr/include/qt/QtWebEngineWidgets -I/usr/include/qt/QtPrintSupport -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtMultimedia -I/usr/include/qt/QtWebEngineCore -I/usr/include/qt/QtQuick -I/usr/include/qt/QtGui -I/usr/include/qt/QtQmlModels -I/usr/include/qt/QtWebChannel -I/usr/include/qt/QtQml -I/usr/include/qt/QtNetwork -I/usr/include/qt/QtBluetooth -I/usr/include/qt/QtDBus -I/usr/include/qt/QtPositioning -I/usr/include/qt/QtCore -I/usr/include/c++/13.2.1 -I/usr/include/c++/13.2.1/x86_64-pc-linux-gnu -I/usr/include/c++/13.2.1/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/13.2.1/include -I/usr/local/include -I/usr/lib/gcc/x86_64-pc-linux-gnu/13.2.1/include-fixed -I/usr/include headers/bt/btUnpair.hpp -o moc/moc_btUnpair.cpp

moc/moc_btDiscoveredDevices.cpp: headers/bt/btDiscoveredDevices.hpp \
		headers/dbus/dbus.hpp \
		moc/moc_predefs.h \
		/usr/bin/moc
	/usr/bin/moc $(DEFINES) --include /home/cappe/School/Lab2/CarHeadUnit/moc/moc_predefs.h -I/usr/lib/qt/mkspecs/linux-g++ -I/home/cappe/School/Lab2/CarHeadUnit -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/qt -I/usr/include/qt/QtWebEngineWidgets -I/usr/include/qt/QtPrintSupport -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtMultimedia -I/usr/include/qt/QtWebEngineCore -I/usr/include/qt/QtQuick -I/usr/include/qt/QtGui -I/usr/include/qt/QtQmlModels -I/usr/include/qt/QtWebChannel -I/usr/include/qt/QtQml -I/usr/include/qt/QtNetwork -I/usr/include/qt/QtBluetooth -I/usr/include/qt/QtDBus -I/usr/include/qt/QtPositioning -I/usr/include/qt/QtCore -I/usr/include/c++/13.2.1 -I/usr/include/c++/13.2.1/x86_64-pc-linux-gnu -I/usr/include/c++/13.2.1/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/13.2.1/include -I/usr/local/include -I/usr/lib/gcc/x86_64-pc-linux-gnu/13.2.1/include-fixed -I/usr/include headers/bt/btDiscoveredDevices.hpp -o moc/moc_btDiscoveredDevices.cpp

moc/moc_btAbstractClass.cpp: headers/bt/btAbstractClass.hpp \
		headers/dbus/dbus.hpp \
		moc/moc_predefs.h \
		/usr/bin/moc
	/usr/bin/moc $(DEFINES) --include /home/cappe/School/Lab2/CarHeadUnit/moc/moc_predefs.h -I/usr/lib/qt/mkspecs/linux-g++ -I/home/cappe/School/Lab2/CarHeadUnit -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/qt -I/usr/include/qt/QtWebEngineWidgets -I/usr/include/qt/QtPrintSupport -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtMultimedia -I/usr/include/qt/QtWebEngineCore -I/usr/include/qt/QtQuick -I/usr/include/qt/QtGui -I/usr/include/qt/QtQmlModels -I/usr/include/qt/QtWebChannel -I/usr/include/qt/QtQml -I/usr/include/qt/QtNetwork -I/usr/include/qt/QtBluetooth -I/usr/include/qt/QtDBus -I/usr/include/qt/QtPositioning -I/usr/include/qt/QtCore -I/usr/include/c++/13.2.1 -I/usr/include/c++/13.2.1/x86_64-pc-linux-gnu -I/usr/include/c++/13.2.1/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/13.2.1/include -I/usr/local/include -I/usr/lib/gcc/x86_64-pc-linux-gnu/13.2.1/include-fixed -I/usr/include headers/bt/btAbstractClass.hpp -o moc/moc_btAbstractClass.cpp

moc/moc_dbus.cpp: headers/dbus/dbus.hpp \
		moc/moc_predefs.h \
		/usr/bin/moc
	/usr/bin/moc $(DEFINES) --include /home/cappe/School/Lab2/CarHeadUnit/moc/moc_predefs.h -I/usr/lib/qt/mkspecs/linux-g++ -I/home/cappe/School/Lab2/CarHeadUnit -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/qt -I/usr/include/qt/QtWebEngineWidgets -I/usr/include/qt/QtPrintSupport -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtMultimedia -I/usr/include/qt/QtWebEngineCore -I/usr/include/qt/QtQuick -I/usr/include/qt/QtGui -I/usr/include/qt/QtQmlModels -I/usr/include/qt/QtWebChannel -I/usr/include/qt/QtQml -I/usr/include/qt/QtNetwork -I/usr/include/qt/QtBluetooth -I/usr/include/qt/QtDBus -I/usr/include/qt/QtPositioning -I/usr/include/qt/QtCore -I/usr/include/c++/13.2.1 -I/usr/include/c++/13.2.1/x86_64-pc-linux-gnu -I/usr/include/c++/13.2.1/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/13.2.1/include -I/usr/local/include -I/usr/lib/gcc/x86_64-pc-linux-gnu/13.2.1/include-fixed -I/usr/include headers/dbus/dbus.hpp -o moc/moc_dbus.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: uic/ui_test.h uic/ui_drawerMenu.h uic/ui_statusBar.h
compiler_uic_clean:
	-$(DEL_FILE) uic/ui_test.h uic/ui_drawerMenu.h uic/ui_statusBar.h
uic/ui_test.h: test.ui \
		/usr/bin/uic
	/usr/bin/uic test.ui -o uic/ui_test.h

uic/ui_drawerMenu.h: ui/drawerMenu.ui \
		/usr/bin/uic
	/usr/bin/uic ui/drawerMenu.ui -o uic/ui_drawerMenu.h

uic/ui_statusBar.h: ui/statusBar.ui \
		/usr/bin/uic
	/usr/bin/uic ui/statusBar.ui -o uic/ui_statusBar.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

obj/APIhandler.o: APIhandler.cpp headers/APIhandler.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/APIhandler.o APIhandler.cpp

obj/appsInterface.o: appsInterface.cpp headers/appsInterface.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/appsInterface.o appsInterface.cpp

obj/audioSystem.o: audioSystem.cpp headers/audioSystem.hpp \
		headers/musicInterface.hpp \
		headers/dbusWorker.hpp \
		headers/bluetooth.hpp \
		headers/utils.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/audioSystem.o audioSystem.cpp

obj/buttonHandler.o: buttonHandler.cpp headers/buttonHandler.hpp \
		headers/toolBar.hpp \
		uic/ui_drawerMenu.h \
		headers/mainWindow.hpp \
		headers/bt/btDeviceListener.hpp \
		headers/musicInterface.hpp \
		headers/mainMenu.hpp \
		uic/ui_test.h \
		customWidgets/customButton.hpp \
		headers/audioSystem.hpp \
		headers/dbusWorker.hpp \
		headers/bluetooth.hpp \
		headers/bluetoothInterface.hpp \
		customWidgets/settingsRow.hpp \
		customWidgets/btDevice.hpp \
		headers/dbus/dbus.hpp \
		headers/bt/btDiscoveredDevices.hpp \
		headers/bt/btDisconnect.hpp \
		headers/bt/btConnect.hpp \
		headers/bt/btAbstractClass.hpp \
		headers/bt/btUnpair.hpp \
		headers/bt/btScan.hpp \
		headers/bt/btPair.hpp \
		headers/appsInterface.hpp \
		headers/navigationInterface.hpp \
		headers/navigationSystem.hpp \
		headers/radioInterface.hpp \
		headers/dataStorage.hpp \
		headers/APIhandler.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/buttonHandler.o buttonHandler.cpp

obj/dataStorage.o: dataStorage.cpp headers/dataStorage.hpp \
		headers/utils.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/dataStorage.o dataStorage.cpp

obj/dbusWorker.o: dbusWorker.cpp headers/dbusWorker.hpp \
		headers/bluetooth.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/dbusWorker.o dbusWorker.cpp

obj/errorHandling.o: errorHandling.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/errorHandling.o errorHandling.cpp

obj/externalInterfaces.o: externalInterfaces.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/externalInterfaces.o externalInterfaces.cpp

obj/internetConnectivity.o: internetConnectivity.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/internetConnectivity.o internetConnectivity.cpp

obj/main.o: main.cpp headers/mainWindow.hpp \
		headers/bt/btDeviceListener.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/main.o main.cpp

obj/mainMenu.o: mainMenu.cpp headers/mainMenu.hpp \
		uic/ui_test.h \
		customWidgets/customButton.hpp \
		headers/buttonHandler.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/mainMenu.o mainMenu.cpp

obj/mainWindow.o: mainWindow.cpp headers/mainWindow.hpp \
		headers/bt/btDeviceListener.hpp \
		headers/toolBar.hpp \
		uic/ui_drawerMenu.h \
		headers/statusBar.hpp \
		uic/ui_statusBar.h \
		headers/mainMenu.hpp \
		uic/ui_test.h \
		customWidgets/customButton.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/mainWindow.o mainWindow.cpp

obj/mediaLibrary.o: mediaLibrary.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/mediaLibrary.o mediaLibrary.cpp

obj/musicInterface.o: musicInterface.cpp headers/musicInterface.hpp \
		headers/buttonHandler.hpp \
		headers/audioSystem.hpp \
		headers/dbusWorker.hpp \
		headers/bluetooth.hpp \
		headers/utils.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/musicInterface.o musicInterface.cpp

obj/navigationInterface.o: navigationInterface.cpp headers/navigationInterface.hpp \
		headers/navigationSystem.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/navigationInterface.o navigationInterface.cpp

obj/navigationSystem.o: navigationSystem.cpp headers/navigationSystem.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/navigationSystem.o navigationSystem.cpp

obj/radioInterface.o: radioInterface.cpp headers/radioInterface.hpp \
		customWidgets/customButton.hpp \
		headers/dataStorage.hpp \
		headers/APIhandler.hpp \
		headers/audioSystem.hpp \
		headers/musicInterface.hpp \
		headers/dbusWorker.hpp \
		headers/bluetooth.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/radioInterface.o radioInterface.cpp

obj/settingsManager.o: settingsManager.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/settingsManager.o settingsManager.cpp

obj/statusBar.o: statusBar.cpp headers/statusBar.hpp \
		uic/ui_statusBar.h \
		headers/buttonHandler.hpp \
		headers/mainWindow.hpp \
		headers/bt/btDeviceListener.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/statusBar.o statusBar.cpp

obj/toolBar.o: toolBar.cpp headers/toolBar.hpp \
		uic/ui_drawerMenu.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/toolBar.o toolBar.cpp

obj/utils.o: utils.cpp headers/utils.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/utils.o utils.cpp

obj/bluetooth.o: bluetooth/bluetooth.cpp headers/bluetooth.hpp \
		headers/bluetoothInterface.hpp \
		customWidgets/settingsRow.hpp \
		customWidgets/btDevice.hpp \
		headers/bt/btDeviceListener.hpp \
		headers/dbus/dbus.hpp \
		headers/bt/btDiscoveredDevices.hpp \
		headers/bt/btDisconnect.hpp \
		headers/bt/btConnect.hpp \
		headers/bt/btAbstractClass.hpp \
		headers/bt/btUnpair.hpp \
		headers/bt/btScan.hpp \
		headers/bt/btPair.hpp \
		headers/dataStorage.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/bluetooth.o bluetooth/bluetooth.cpp

obj/bluetoothInterface.o: bluetooth/bluetoothInterface.cpp headers/bluetoothInterface.hpp \
		customWidgets/settingsRow.hpp \
		customWidgets/btDevice.hpp \
		headers/bt/btDeviceListener.hpp \
		headers/dbus/dbus.hpp \
		headers/bt/btDiscoveredDevices.hpp \
		headers/bt/btDisconnect.hpp \
		headers/bt/btConnect.hpp \
		headers/bt/btAbstractClass.hpp \
		headers/bt/btUnpair.hpp \
		headers/bt/btScan.hpp \
		headers/bt/btPair.hpp \
		headers/bluetooth.hpp \
		headers/dataStorage.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/bluetoothInterface.o bluetooth/bluetoothInterface.cpp

obj/btConnect.o: bluetooth/btConnect.cpp headers/bt/btConnect.hpp \
		headers/dbus/dbus.hpp \
		headers/bt/btAbstractClass.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/btConnect.o bluetooth/btConnect.cpp

obj/btDeviceListener.o: bluetooth/btDeviceListener.cpp headers/bt/btDeviceListener.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/btDeviceListener.o bluetooth/btDeviceListener.cpp

obj/btDisconnect.o: bluetooth/btDisconnect.cpp headers/bt/btDisconnect.hpp \
		headers/dbus/dbus.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/btDisconnect.o bluetooth/btDisconnect.cpp

obj/btPair.o: bluetooth/btPair.cpp headers/bt/btPair.hpp \
		headers/dbus/dbus.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/btPair.o bluetooth/btPair.cpp

obj/btScan.o: bluetooth/btScan.cpp headers/bt/btScan.hpp \
		headers/dbus/dbus.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/btScan.o bluetooth/btScan.cpp

obj/btUnpair.o: bluetooth/btUnpair.cpp headers/bt/btUnpair.hpp \
		headers/dbus/dbus.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/btUnpair.o bluetooth/btUnpair.cpp

obj/btDiscoveredDevices.o: bluetooth/btDiscoveredDevices.cpp headers/bt/btDiscoveredDevices.hpp \
		headers/dbus/dbus.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/btDiscoveredDevices.o bluetooth/btDiscoveredDevices.cpp

obj/btDevice.o: customWidgets/btDevice.cpp customWidgets/btDevice.hpp \
		headers/bt/btDeviceListener.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/btDevice.o customWidgets/btDevice.cpp

obj/customButton.o: customWidgets/customButton.cpp customWidgets/customButton.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/customButton.o customWidgets/customButton.cpp

obj/settingsRow.o: customWidgets/settingsRow.cpp customWidgets/settingsRow.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/settingsRow.o customWidgets/settingsRow.cpp

obj/dbus.o: dbus/dbus.cpp headers/dbus/dbus.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/dbus.o dbus/dbus.cpp

obj/moc_btDevice.o: moc/moc_btDevice.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_btDevice.o moc/moc_btDevice.cpp

obj/moc_customButton.o: moc/moc_customButton.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_customButton.o moc/moc_customButton.cpp

obj/moc_settingsRow.o: moc/moc_settingsRow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_settingsRow.o moc/moc_settingsRow.cpp

obj/moc_APIhandler.o: moc/moc_APIhandler.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_APIhandler.o moc/moc_APIhandler.cpp

obj/moc_bluetooth.o: moc/moc_bluetooth.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_bluetooth.o moc/moc_bluetooth.cpp

obj/moc_bluetoothInterface.o: moc/moc_bluetoothInterface.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_bluetoothInterface.o moc/moc_bluetoothInterface.cpp

obj/moc_buttonHandler.o: moc/moc_buttonHandler.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_buttonHandler.o moc/moc_buttonHandler.cpp

obj/moc_dbusWorker.o: moc/moc_dbusWorker.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_dbusWorker.o moc/moc_dbusWorker.cpp

obj/moc_mainMenu.o: moc/moc_mainMenu.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_mainMenu.o moc/moc_mainMenu.cpp

obj/moc_mainWindow.o: moc/moc_mainWindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_mainWindow.o moc/moc_mainWindow.cpp

obj/moc_navigationInterface.o: moc/moc_navigationInterface.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_navigationInterface.o moc/moc_navigationInterface.cpp

obj/moc_radioInterface.o: moc/moc_radioInterface.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_radioInterface.o moc/moc_radioInterface.cpp

obj/moc_statusBar.o: moc/moc_statusBar.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_statusBar.o moc/moc_statusBar.cpp

obj/moc_toolBar.o: moc/moc_toolBar.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_toolBar.o moc/moc_toolBar.cpp

obj/moc_btConnect.o: moc/moc_btConnect.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_btConnect.o moc/moc_btConnect.cpp

obj/moc_btDeviceListener.o: moc/moc_btDeviceListener.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_btDeviceListener.o moc/moc_btDeviceListener.cpp

obj/moc_btDisconnect.o: moc/moc_btDisconnect.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_btDisconnect.o moc/moc_btDisconnect.cpp

obj/moc_btPair.o: moc/moc_btPair.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_btPair.o moc/moc_btPair.cpp

obj/moc_btScan.o: moc/moc_btScan.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_btScan.o moc/moc_btScan.cpp

obj/moc_btUnpair.o: moc/moc_btUnpair.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_btUnpair.o moc/moc_btUnpair.cpp

obj/moc_btDiscoveredDevices.o: moc/moc_btDiscoveredDevices.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_btDiscoveredDevices.o moc/moc_btDiscoveredDevices.cpp

obj/moc_btAbstractClass.o: moc/moc_btAbstractClass.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_btAbstractClass.o moc/moc_btAbstractClass.cpp

obj/moc_dbus.o: moc/moc_dbus.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_dbus.o moc/moc_dbus.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

